# -*- coding: utf-8 -*-
"""Group11_Section2.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Yhnq5JVnBM5uf02RCq-JFatF4zhsi0f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report,confusion_matrix, ConfusionMatrixDisplay
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

sdd= pd.read_csv('/content/input.csv')
sdd.head()

sdd.shape

sdd.dtypes

sdd.columns

sdd.info()

#counting drinking class
totalclass_count= sdd['DRK_YN'].value_counts()
print(totalclass_count)

#counting smoking class
totalclass_counts = sdd['SMK_stat_type_cd'].value_counts()
print(totalclass_counts)

sns.countplot(x = 'SMK_stat_type_cd', data=sdd, label='count')
plt.show()
sns.countplot(x = 'DRK_YN', data=sdd, label='count')
plt.show()

sdd['sex'].value_counts()

calculatefemalesdd = sdd[sdd['sex'] == 'Female']
total_female = len(calculatefemalesdd)
drinker_female = len(calculatefemalesdd[calculatefemalesdd['DRK_YN']=='Y'])
smoker_female = len(calculatefemalesdd[calculatefemalesdd['SMK_stat_type_cd']== 3])


calculatemalesdd = sdd[sdd['sex'] == 'Male']
total_male = len(calculatemalesdd)
drinker_male = len(calculatemalesdd[calculatemalesdd['DRK_YN']=='Y'])
smoker_male = len(calculatemalesdd[calculatemalesdd['SMK_stat_type_cd']==3])

percentage_of_femaledrinker = '{:.1f}'.format((drinker_female/total_female)*100)
print('Percentage of female drinkers:', percentage_of_femaledrinker,'%')
percentage_of_maledrinker = '{:.1f}'.format((drinker_male/total_male)*100)
print('Percentage of male drinkers:', percentage_of_maledrinker,'%')

percentage_of_smoker_female = '{:.1f}'.format((smoker_female/total_female)*100)
print('Percentage of female smokers:', percentage_of_smoker_female,'%')
percentage_of_smoker_male = '{:.1f}'.format((smoker_male/total_male)*100)
print('Percentage of male smokers:', percentage_of_smoker_male,'%')

labels = ['Male', 'Female']
explode = (0, 0.1)
sizes = [percentage_of_maledrinker, percentage_of_femaledrinker]
colors = ['orange', 'peachpuff']

plt.figure(figsize=(7, 5))
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', shadow=True, startangle=140)
plt.title('Percentage of Male and Female Who drink')
plt.axis('equal')
plt.show()

labels = ['Male', 'Female']
explode = (0, 0.1)
sizes = [percentage_of_smoker_male, percentage_of_smoker_female]
colors = ['orange', 'peachpuff']

plt.figure(figsize=(7, 5))
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', shadow=True, startangle=140)
plt.title('Percentage of Male and Female Who smoke')
plt.axis('equal')
plt.show()

counting_femalesmokers = calculatefemalesdd['SMK_stat_type_cd'].value_counts()
never_femalesmokers = counting_femalesmokers.get(1,0)
current_femalesmokers = counting_femalesmokers.get(3,0)
past_femalesmokers = counting_femalesmokers.get(2,0)

counting_male_smokers = calculatemalesdd['SMK_stat_type_cd'].value_counts()
never_malesmokers = counting_male_smokers.get(1,0)
current_malesmokers = counting_male_smokers.get(3,0)
past_malesmokers = counting_male_smokers.get(2,0)

print('Current females smokers:', current_femalesmokers)
print('Past female smokers:', past_femalesmokers)
print('Females who never smoked:', never_femalesmokers)

print('Current males smokers:', current_malesmokers)
print('Past male smokers:', past_malesmokers)
print('Males who never smoked:', never_malesmokers)

features = sdd.shape[1]
print(features)

sdd1 = sdd.copy()
sex1=lambda x: 1 if x=='Male' else 0
sdd1['sex'] = sdd['sex'].apply(sex1)
drykn1=lambda x:1 if x=='Y' else 0
sdd1['DRK_YN'] = sdd['DRK_YN'].apply(drykn1)
smk1=lambda x:1 if x== 3 else 0
sdd1['SMK_stat_type_cd'] = sdd['SMK_stat_type_cd'].apply(smk1)

sdd1.info()

"""## **Working** **on** **null** **values**"""

sdd1.isnull().sum()
total_null_values = sdd1.isnull().sum().sum()
print(total_null_values)

sdd1.isnull().sum()

matrix_of_correlation = sdd1.corr()
plt.figure(figsize = (10,8))
sns.heatmap(matrix_of_correlation, annot = True, cmap = 'BrBG', fmt = '.2f', linewidths=0.5, annot_kws={"size": 6})
plt.title('Correlation Heatmap')
plt.show()

data_points = sdd.shape[0]
print(data_points)

"""# **Feature** **Scaling** **MinMax** **Scaler**"""

from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


X = sdd1.drop(['SMK_stat_type_cd', 'DRK_YN'], axis =1)
y_drykn = sdd1['DRK_YN']
y_smk = sdd1['SMK_stat_type_cd']
X_train, X_test, y_drykn_train, y_drykn_test, y_smk_train, y_smk_test = train_test_split(X, y_drykn, y_smk, test_size= 0.4, random_state= 51)

dri1 = RandomOverSampler(random_state=51)
X_train_drink_resampling , y_train_drink_resampling = dri1.fit_resample(X_train, y_drykn_train)

smok1 = RandomOverSampler(random_state=51)
X_train_smoke_resampling , y_train_smoke_resampling = dri1.fit_resample(X_train, y_smk_train)

from sklearn.preprocessing import MinMaxScaler
drinking_scale = MinMaxScaler()
X_train_drink_scaled = drinking_scale.fit_transform(X_train_drink_resampling)

smoking_scale = MinMaxScaler()
X_train_smoke_scaled= smoking_scale.fit_transform(X_train_smoke_resampling)

X_test_drink_scaled = drinking_scale.transform(X_test)
X_test_smoke_scaled = smoking_scale.transform(X_test)

print(X_test_drink_scaled)
print(X_test_smoke_scaled)
print('Minimum value of per feature after scaling:\n{}'.format(X_train_smoke_scaled.min(axis=0)))
print('Maximum value of per feature after scaling:\n{}'.format(X_train_smoke_scaled.max(axis=0)))
print('Minimum value of per feature after scaling:\n{}'.format(X_train_drink_scaled.min(axis=0)))
print('Maximum value of per feature after scaling:\n{}'.format(X_train_drink_scaled.max(axis=0)))

"""# **KNN** **MODEL**"""

print("\nPrediction for KNN Smoking:")
knn_var1 = KNeighborsClassifier(n_neighbors =75)
knn_var1.fit(X_train_smoke_scaled, y_train_smoke_resampling)
prediction_smoke_knn = knn_var1.predict(X_test_smoke_scaled)
accuracy_smoke_knn = accuracy_score(y_smk_test, prediction_smoke_knn)
class_report_smoke = classification_report(y_smk_test, prediction_smoke_knn)
print(f'Smoking Accuracy: {accuracy_smoke_knn:.4f}')
print('\nReport:')
print(class_report_smoke)


print("\nPrediction for KNN Drinking:")
knn_var1 = KNeighborsClassifier(n_neighbors =75)
knn_var1.fit(X_train_drink_scaled, y_train_drink_resampling)
prediction_drink_knn = knn_var1.predict(X_test_drink_scaled)
accuracy_drink_knn = accuracy_score(y_drykn_test, prediction_drink_knn)
class_report_drink = classification_report(y_drykn_test, prediction_drink_knn)
print(f'Drnking Accuracy: {accuracy_drink_knn:.4f}')
print('\nReport:')
print(class_report_drink)

"""## **Naive** **Bayes**"""

print("\nPrediction for Naive Bayes Smoking:")
naive_bayes_var1 = GaussianNB()
naive_bayes_var1.fit(X_train_smoke_scaled, y_train_smoke_resampling)
prediction_smoke_naive_bayes = naive_bayes_var1.predict(X_test_smoke_scaled)
accuracy_smoke_naive_bayes = accuracy_score(y_smk_test, prediction_smoke_naive_bayes)
class_report_smoke = classification_report(y_smk_test, prediction_smoke_naive_bayes)

print(f'Smoking Accuracy: {accuracy_smoke_naive_bayes:.4f}')
print('\nReport:')
print(class_report_smoke)


print("\nPrediction Naive Bayes Drinking:")
naive_bayes_var1 = GaussianNB()
naive_bayes_var1.fit(X_train_drink_scaled, y_train_drink_resampling)
prediction_drink_naive_bayes = naive_bayes_var1.predict(X_test_drink_scaled)
accuracy_drink_naive_bayes = accuracy_score(y_drykn_test, prediction_drink_naive_bayes)
class_report_drink = classification_report(y_drykn_test, prediction_drink_naive_bayes)

print(f'Drinking Accuracy: {accuracy_drink_naive_bayes:.4f}')
print('\nReport:')
print(class_report_drink)

"""## **Decision** **Tree** **Model**"""

from sklearn.tree import DecisionTreeClassifier

# For Drinking Prediction
decision_tree_classifier_drink = DecisionTreeClassifier(random_state=42)
decision_tree_classifier_drink.fit(X_train_drink_scaled, y_train_drink_resampling)

dt_pred_drink = decision_tree_classifier_drink.predict(X_test_drink_scaled)

dt_accuracy_drink = accuracy_score(y_drykn_test, dt_pred_drink)
class_report_drink = classification_report(y_drykn_test, dt_pred_drink)

print("\nDecision Tree - For Drinking Prediction:")
print(f'Accuracy: {dt_accuracy_drink:.4f}')
print('\nClassification Report:')
print(class_report_drink)

# For Smoking Prediction
decision_tree_classifier_smoke = DecisionTreeClassifier(random_state=42)
decision_tree_classifier_smoke.fit(X_train_smoke_scaled, y_train_smoke_resampling)

dt_pred_smoke = decision_tree_classifier_smoke.predict(X_test_smoke_scaled)

dt_accuracy_smoke = accuracy_score(y_smk_test, dt_pred_smoke)
class_report_smoke = classification_report(y_smk_test, dt_pred_smoke)

print("\nDecision Tree - For Smoking Prediction:")
print(f'Accuracy: {dt_accuracy_smoke:.4f}')
print('\nClassification Report:')
print(class_report_smoke)

"""# **Graphs** **Plotting**"""

models = ['KNN',  'Naive\nBayes',  'Decision\nTree']

mappingaccuracies_1 = [accuracy_smoke_knn, accuracy_smoke_naive_bayes,dt_accuracy_smoke]
plt.bar(models, mappingaccuracies_1, color = ['lightblue', 'lightgreen', 'orange'])
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title('Accuracy prediction - Smoking')
plt.show()

mappingaccuracies_2 = [accuracy_drink_knn,accuracy_drink_naive_bayes,dt_accuracy_drink]
plt.bar(models, mappingaccuracies_2, color = ['lightblue', 'lightgreen', 'orange'])
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title('Accuracy prediction - Drinking')
plt.show()

#KNN
precision_of_knn_1 = precision_score(y_drykn_test, prediction_drink_knn)
recall_score_knn_1 = recall_score(y_drykn_test, prediction_drink_knn)
precision_of_knn_2 = precision_score(y_smk_test, prediction_smoke_knn)
recall_score_knn_2 = recall_score(y_smk_test, prediction_smoke_knn)

#Naive Bayes
precision_of_naive_bayes_1 = precision_score(y_drykn_test, prediction_drink_naive_bayes)
recall_score_knn_naive_bayes_1 = recall_score(y_drykn_test, prediction_drink_naive_bayes)
precision_of_naive_bayes_2 = precision_score(y_smk_test, prediction_smoke_naive_bayes)
recall_score_knn_naive_bayes_2 = recall_score(y_smk_test, prediction_smoke_naive_bayes)

#Decision Tree
dt_precision_1 = precision_score(y_drykn_test,dt_pred_drink)
dt_recall_1 = recall_score(y_drykn_test, dt_pred_drink)
dt_precision_2 = precision_score(y_smk_test, dt_pred_smoke)
dt_recall_2 = recall_score(y_smk_test, dt_pred_smoke)



precise_1 = [precision_of_knn_1,  precision_of_naive_bayes_1, dt_precision_1]
recall_score_1 = [ recall_score_knn_1,  recall_score_knn_naive_bayes_1, dt_recall_1]
precise_2 = [precision_of_knn_2,  precision_of_naive_bayes_2, dt_precision_2]
recall_score_2 = [ recall_score_knn_2,  recall_score_knn_naive_bayes_2,  dt_recall_2]

#graph plotting for smoking
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4))
ax1.bar(models, precise_1, color=['lightblue', 'lightgreen', 'orange'])
ax1.set_ylim(0, 1)
ax1.set_ylabel('Precision')
ax1.set_title('Precision Comparison - Smoking')
ax2.bar(models, recall_score_1, color=['lightblue', 'lightgreen', 'orange'])
ax2.set_ylim(0, 1)
ax2.set_ylabel('Recall')
ax2.set_title('Recall Score Comparison - Smoking')
plt.tight_layout()
plt.show()

#graph plotting for drinking
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4))
ax1.bar(models, precise_2, color=['lightblue', 'lightgreen', 'orange'])
ax1.set_ylim(0, 1)
ax1.set_ylabel('Precision')
ax1.set_title('Precision Comparison - Drinking')
ax2.bar(models, recall_score_2, color=['lightblue', 'lightgreen', 'orange'])
ax2.set_ylim(0, 1)
ax2.set_ylabel('Recall')
ax2.set_title('Recall Score Comparison - Drinking')
plt.tight_layout()
plt.show()

#knn
f1score_knn_1 = f1_score(y_drykn_test, prediction_drink_knn)
f1score_knn_2 = f1_score(y_smk_test, prediction_smoke_knn)

#naive bayes
f1score_naive_bayes_1 = f1_score(y_drykn_test, prediction_drink_naive_bayes)
f1score_naive_bayes_2 = f1_score(y_smk_test, prediction_smoke_naive_bayes)

#decision tree
dt_f1_score_1 = f1_score(y_drykn_test, dt_pred_drink)
dt_f1_score_2 = f1_score(y_smk_test, dt_pred_smoke)


f1_score_1 = [f1score_knn_1,  f1score_naive_bayes_1, dt_f1_score_1]
f1_score_2 = [f1score_knn_2,  f1score_naive_bayes_2, dt_f1_score_2]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))

#Smoking
ax1.bar(models, f1_score_2, color=['grey', 'lightgreen', 'orange'])
ax1.set_ylim(0, 1)
ax1.set_ylabel('F1 Score')
ax1.set_title('F1 Score Comparison - Smoking')

#Drinking
ax2.bar(models, f1_score_1, color=['grey', 'lightgreen', 'orange'])
ax2.set_ylim(0, 1)
ax2.set_ylabel('F1 Score')
ax2.set_title('F1 Score Comparison - Drinking')

plt.tight_layout()
plt.show()

#smokinh
conf_matrixsmoke_knn = confusion_matrix(y_smk_test, prediction_smoke_knn)
conf_matrixsmoke_naive_bayes = confusion_matrix(y_smk_test, prediction_smoke_naive_bayes)
conf_matrixsmoke_dt = confusion_matrix(y_smk_test, dt_pred_smoke)

fig, axes = plt.subplots(1, 3, figsize=(12, 4))

ConfusionMatrixDisplay(conf_matrixsmoke_knn, display_labels=['Negative', 'Positive']).plot(ax=axes[0], cmap=plt.cm.Blues, values_format='.2f')
axes[0].set_title(f'{models[0]} Confusion Matrix - Smoking')

ConfusionMatrixDisplay(conf_matrixsmoke_naive_bayes, display_labels=['Negative', 'Positive']).plot(ax=axes[1], cmap=plt.cm.Greens, values_format='.2f')
axes[1].set_title(f'{models[1]} Confusion Matrix - Smoking')

ConfusionMatrixDisplay(conf_matrixsmoke_dt, display_labels=['Negative', 'Positive']).plot(ax=axes[2], cmap=plt.cm.Reds, values_format='.2f')
axes[2].set_title(f'{models[2]} Confusion Matrix - Smoking')

plt.tight_layout()
plt.show()

#drinking
conf_matrixdrink_knn = confusion_matrix(y_drykn_test, prediction_drink_knn)
conf_matrixdrink_naive_bayes = confusion_matrix(y_drykn_test, prediction_drink_naive_bayes)
conf_matrixdrink_dt = confusion_matrix(y_drykn_test, dt_pred_drink)

fig, axes = plt.subplots(1, 3, figsize=(12, 4))  # Create a 1x3 grid for drinking confusion matrices

ConfusionMatrixDisplay(conf_matrixdrink_knn, display_labels=['Negative', 'Positive']).plot(ax=axes[0], cmap=plt.cm.Blues, values_format='.2f')
axes[0].set_title(f'{models[0]} Confusion Matrix - Drinking')

ConfusionMatrixDisplay(conf_matrixdrink_naive_bayes, display_labels=['Negative', 'Positive']).plot(ax=axes[1], cmap=plt.cm.Greens, values_format='.2f')
axes[1].set_title(f'{models[1]} Confusion Matrix - Drinking')

ConfusionMatrixDisplay(conf_matrixdrink_dt, display_labels=['Negative', 'Positive']).plot(ax=axes[2], cmap=plt.cm.Reds, values_format='.2f')
axes[2].set_title(f'{models[2]} Confusion Matrix - Drinking')

plt.tight_layout()
plt.show()